import java.awt.Font;
import java.awt.event.ActionListener;
import java.beans.EventHandler;

public class FontFrameMatisse extends javax.swing.JFrame {
        
    public FontFrameMatisse() {
        initComponents();
        updateSample();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ActionListener listener = EventHandler.create(ActionListener.class, this, "updateSample");
        faceLabel = new javax.swing.JLabel();
        sizeLabel = new javax.swing.JLabel();
        face = new javax.swing.JComboBox<>();
        size = new javax.swing.JComboBox<>();
        bold = new javax.swing.JCheckBox();
        bold.addActionListener(listener);
        italic = new javax.swing.JCheckBox();
        italic.addActionListener(listener);
        sampleScrollPane = new javax.swing.JScrollPane();
        sample = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("FontFrameMatisse");
        setMinimumSize(new java.awt.Dimension(300, 250));
        setName("fontFrameMatisse"); // NOI18N
        setPreferredSize(new java.awt.Dimension(430, 250));

        faceLabel.setText("Face:");

        sizeLabel.setText("Size:");

        face.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Serif", "SansSerif", "Monospaced", "Dialog", "DialogInput" }));
        face.addActionListener(listener);

        size.setModel(new javax.swing.DefaultComboBoxModel<>(new Integer[] {8, 10, 12, 15, 18, 24, 36}));
        size.setSelectedIndex(2);
        size.addActionListener(listener);

        bold.setText("Bold");

        italic.setText("Italic");

        sample.setColumns(20);
        sample.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        sample.setRows(10);
        sample.setText("The quick brown fox jumps over the lazy dog");
        sampleScrollPane.setViewportView(sample);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(faceLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(sizeLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(face, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(size, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bold)
                    .addComponent(italic))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(sampleScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(faceLabel)
                            .addComponent(face, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sizeLabel)
                            .addComponent(size, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(bold)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(italic)
                        .addContainerGap(102, Short.MAX_VALUE))
                    .addComponent(sampleScrollPane)))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {bold, face, faceLabel, italic, size, sizeLabel});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void updateSample() {
        String fontFace = (String) face.getSelectedItem();
        int fontStyle = (bold.isSelected() ? Font.BOLD : 0) + (italic.isSelected() ? Font.ITALIC : 0);
        int fontSize = size.getItemAt(size.getSelectedIndex());
        Font font = new Font(fontFace, fontStyle, fontSize);
        sample.setFont(font);
        sample.repaint();
    }
    
    public static void main(String args[]) {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FontFrameMatisse().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox bold;
    private javax.swing.JComboBox<String> face;
    private javax.swing.JLabel faceLabel;
    private javax.swing.JCheckBox italic;
    private javax.swing.JTextArea sample;
    private javax.swing.JScrollPane sampleScrollPane;
    private javax.swing.JComboBox<Integer> size;
    private javax.swing.JLabel sizeLabel;
    // End of variables declaration//GEN-END:variables
}
